Fix NoSuchMethodException in getReportsDirectory
After building the "sonar scala" plugin from master, and installing in Sonar v4.1.1, I received the following error when running mvn sonar:sonar

java.lang.NoSuchMethodError: org.sonar.plugins.surefire.api.SurefireUtils.getReportsDirectory(Lorg/sonar/api/resources/Project;)Ljava/io/File;
at org.sonar.plugins.scala.surefire.SurefireSensor.analyse(SurefireSensor.java:51)
at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:72)

The "objective-c plugin" hit the same issue which they fixed here:
https://github.com/drewcrawford/sonar-objective-c/commit/ec68e769aef8675eb3f5a748d853741461c5d9c6

I modified their solution to use getFileSystem().resolvePath so that Maven multi-module builds will also work.